In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
app_train=pd.read_csv("train.csv")

In [3]:
app_test=pd.read_csv("test.csv")

In [8]:
#concatenate test and train
df = pd.concat([app_train,app_test],axis=0,sort=False)

In [ ]:
# Checking for outliers in the continuous variables
num = df[['interest_rate','unpaid_principal_bal','loan_term','loan_to_value','number_of_borrowers','debt_to_income_ratio','insurance_percent','co-borrower_credit_score','insurance_type']]

In [7]:
app_train['SOOURCE']='train'
app_test['SOOURCE']='test'

In [124]:
app_test.shape

(49739, 29)

In [78]:
catagorical_columns=df.select_dtypes(include='object')


In [79]:
numerical_columns=df.select_dtypes(exclude='object')

In [80]:
catagorical_columns.columns

Index(['source', 'financial_institution', 'first_payment_date', 'loan_purpose',
       'SOOURCE', 'origination_date_Dayweek'],
      dtype='object')

In [81]:
numerical_columns.columns

Index(['loan_id', 'interest_rate', 'unpaid_principal_bal', 'loan_term',
       'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio',
       'borrower_credit_score', 'insurance_percent',
       'co-borrower_credit_score', 'insurance_type', 'm1', 'm2', 'm3', 'm4',
       'm5', 'm6', 'm7', 'm8', 'm9', 'm10', 'm11', 'm12', 'm13',
       'origination_date_quarter', 'origination_date_day',
       'origination_date_Dayofweek', 'origination_date_is_weekend',
       'origination_date_Year'],
      dtype='object')

In [13]:
df['origination_date_new'] = pd.to_datetime(df.origination_date)

In [18]:
df['origination_date_quarter'] = df['origination_date_new'].dt.quarter

In [19]:
df['origination_date_day'] = df['origination_date_new'].dt.day

In [20]:
df['origination_date_Dayofweek'] = df['origination_date_new'].dt.dayofweek

In [22]:
# day of the week - name
df['origination_date_Dayweek'] = df['origination_date_new'].dt.weekday_name

In [23]:
df[['origination_date_Dayweek', 'origination_date_new']].head()

origination_date_Dayweek origination_date_new
0                 Thursday           2012-03-01
1                   Sunday           2012-01-01
2                   Sunday           2012-01-01
3                Wednesday           2012-02-01
4                Wednesday           2012-02-01

In [24]:
# was the application done on the weekend?
df['origination_date_is_weekend'] = np.where(df['origination_date_Dayweek'].isin(['Sunday', 'Saturday']), 1,0)

In [25]:
df['origination_date_Year'] = df['origination_date_new'].dt.year

In [26]:
df.origination_date_Year.value_counts()

2012    165797
Name: origination_date_Year, dtype: int64

In [31]:
df.first_payment_date.replace({'04/2012':"April",'03/2012':"March",'05/2012':"May",'02/2012':"Feb"},inplace=True)

In [82]:
catagorical_columns.head()

source       financial_institution first_payment_date loan_purpose SOOURCE  \
0      Z  Turner, Baldwin and Rhodes                May          C86   train   
1      Y  Swanson, Newton and Miller              March          B12   train   
2      Z              Thornton-Davis              March          B12   train   
3      X                       OTHER              April          B12   train   
4      X                       OTHER              April          C86   train   

  origination_date_Dayweek  
0                 Thursday  
1                   Sunday  
2                   Sunday  
3                Wednesday  
4                Wednesday

In [34]:
df.drop(columns=["origination_date"],inplace=True)

In [77]:
df.drop(columns=["origination_date_new"],inplace=True)

In [40]:
encode=pd.get_dummies(catagorical_columns.drop(columns=["SOOURCE"]))

In [83]:
encode.head()

source_X  source_Y  source_Z  financial_institution_Anderson-Taylor  \
0         0         0         1                                      0   
1         0         1         0                                      0   
2         0         0         1                                      0   
3         1         0         0                                      0   
4         1         0         0                                      0   

   financial_institution_Browning-Hart  financial_institution_Chapman-Mcmahon  \
0                                    0                                      0   
1                                    0                                      0   
2                                    0                                      0   
3                                    0                                      0   
4                                    0                                      0   

   financial_institution_Cole, Brooks and Vincent  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   financial_institution_Edwards-Hoffman  \
0                                      0   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   financial_institution_Martinez, Duffy and Bird  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   financial_institution_Miller, Mcclure and Allen  \
0                                                0   
1                                                0   
2                                                0   
3                                                0   
4                                                0   

                  ...                  first_payment_date_April  \
0                 ...                                         0   
1                 ...                                         0   
2                 ...                                         0   
3                 ...                                         1   
4                 ...                                         1   

   first_payment_date_Feb  first_payment_date_March  first_payment_date_May  \
0                       0                         0                       1   
1                       0                         1                       0   
2                       0                         1                       0   
3                       0                         0                       0   
4                       0                         0                       0   

   loan_purpose_A23  loan_purpose_B12  loan_purpose_C86  \
0                 0                 0                 1   
1                 0                 1                 0   
2                 0                 1                 0   
3                 0                 1                 0   
4                 0                 0                 1   

   origination_date_Dayweek_Sunday  origination_date_Dayweek_Thursday  \
0                                0                                  1   
1                                1                                  0   
2                                1                                  0   
3                                0                                  0   
4                                0                                  0   

   origination_date_Dayweek_Wednesday  
0                                   0  
1                                   0  
2                                   0  
3          

In [84]:
numerical_columns.head()

loan_id  interest_rate  unpaid_principal_bal  loan_term  \
0  268055008619          4.250                214000        360   
1  672831657627          4.875                144000        360   
2  742515242108          3.250                366000        180   
3  601385667462          4.750                135000        360   
4  273870029961          4.750                124000        360   

   loan_to_value  number_of_borrowers  debt_to_income_ratio  \
0             95                  1.0                  22.0   
1             72                  1.0                  44.0   
2             49                  1.0                  33.0   
3             46                  2.0                  44.0   
4             80                  1.0                  43.0   

   borrower_credit_score  insurance_percent  co-borrower_credit_score  \
0                  694.0               30.0                       0.0   
1                  697.0                0.0                       0.0   
2                  780.0                0.0                       0.0   
3                  633.0                0.0                     638.0   
4                  681.0                0.0                       0.0   

           ...            m9  m10  m11  m12  m13  origination_date_quarter  \
0          ...             0    0    0    0  1.0                         1   
1          ...             0    0    1    0  1.0                         1   
2          ...             0    0    0    0  1.0                         1   
3          ...             1    1    1    1  1.0                         1   
4          ...             8    9   10   11  1.0                         1   

   origination_date_day  origination_date_Dayofweek  \
0                     1                           3   
1                     1                           6   
2                     1                           6   
3                     1                           2   
4                     1                           2   

   origination_date_is_weekend  origination_date_Year  
0                            0                   2012  
1                            1                   2012  
2                            1                   2012  
3                            0                   2012  
4                            0                   2012  

[5 rows x 29 columns]

In [85]:
processing_final=pd.concat([encode,numerical_columns,df[["SOOURCE"]]],axis=1)

In [86]:
pre_train = processing_final.loc[processing_final['SOOURCE']=="train"]

In [87]:
pre_test = processing_final.loc[processing_final['SOOURCE']=="test"]

In [88]:
del pre_train["SOOURCE"]


In [89]:

del pre_test["SOOURCE"]

In [90]:
pre_test['loan_id'].head()

0    196706376986
1    786051527565
2    100072474882
3    328189712657
4    577598812667
Name: loan_id, dtype: int64

In [91]:

final=pre_test[["loan_id","m13"]]

In [92]:

del pre_train["loan_id"]

In [93]:
del pre_test["loan_id"]

In [94]:

final.head()

loan_id  m13
0  196706376986  NaN
1  786051527565  NaN
2  100072474882  NaN
3  328189712657  NaN
4  577598812667  NaN

In [95]:
X=pre_train.drop(columns=["m13"],axis=0)

In [96]:
y=pre_train.m13

In [97]:
pre_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 116058 entries, 0 to 116057
Data columns (total 60 columns):
source_X                                             116058 non-null uint8
source_Y                                             116058 non-null uint8
source_Z                                             116058 non-null uint8
financial_institution_Anderson-Taylor                116058 non-null uint8
financial_institution_Browning-Hart                  116058 non-null uint8
financial_institution_Chapman-Mcmahon                116058 non-null uint8
financial_institution_Cole, Brooks and Vincent       116058 non-null uint8
financial_institution_Edwards-Hoffman                116058 non-null uint8
financial_institution_Martinez, Duffy and Bird       116058 non-null uint8
financial_institution_Miller, Mcclure and Allen      116058 non-null uint8
financial_institution_Nicholson Group                116058 non-null uint8
financial_institution_OTHER                          116058 non-

In [98]:
from sklearn import datasets
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

rfe = RFE(logreg, 18)
rfe = rfe.fit(X,y)
print(rfe.support_)
print(rfe.ranking_)

[ True  True  True False False False False False False False False False
 False False False False False False False  True False False False False
 False False False False False  True  True  True  True False False False
  True False False False False  True  True False False  True False False
  True False  True False  True  True False False  True  True False]
[ 1  1  1 40 16 35 15  7 27 14 39 24 25 37 38 21 12 11 17  1 36 22  9 20
 10  8  3  5  4  1  1  1  1 34 32 30  1 26 28 29 33  1  1 13  2  1 18 19
  1  6  1 23  1  1 41 42  1  1 31]


In [149]:
pre_train.columns

Index(['source_X', 'source_Y', 'source_Z',
       'financial_institution_Anderson-Taylor',
       'financial_institution_Browning-Hart',
       'financial_institution_Chapman-Mcmahon',
       'financial_institution_Cole, Brooks and Vincent',
       'financial_institution_Edwards-Hoffman',
       'financial_institution_Martinez, Duffy and Bird',
       'financial_institution_Miller, Mcclure and Allen',
       'financial_institution_Nicholson Group', 'financial_institution_OTHER',
       'financial_institution_Richards-Walters',
       'financial_institution_Richardson Ltd',
       'financial_institution_Romero, Woods and Johnson',
       'financial_institution_Sanchez, Hays and Wilkerson',
       'financial_institution_Sanchez-Robinson',
       'financial_institution_Suarez Inc',
       'financial_institution_Swanson, Newton and Miller',
       'financial_institution_Taylor, Hunt and Rodriguez',
       'financial_institution_Thornton-Davis',
       'financial_institution_Turner, Baldwin

In [198]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [199]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [169]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression(class_weight='balanced')
logreg.fit(X_train_scaled, y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [200]:
logreg = LogisticRegression(class_weight='balanced')
logreg.fit(X_train_scaled, y_train)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [201]:
y_pred_train = logreg.predict(X_train_scaled)

In [202]:

metrics.confusion_matrix(y_train,y_pred_train)

array([[73362,  7427],
       [  110,   341]], dtype=int64)

In [203]:

metrics.f1_score(y_train,y_pred_train)

0.08297846453339822

In [173]:

metrics.recall_score(y_train,y_pred_train)

0.7583148558758315

In [174]:

metrics.precision_score(y_train,y_pred_train)

0.04897608477731634

In [204]:
print(metrics.classification_report(y_train,y_pred_train))

             precision    recall  f1-score   support

        0.0       1.00      0.91      0.95     80789
        1.0       0.04      0.76      0.08       451

avg / total       0.99      0.91      0.95     81240



In [205]:
y_pred = logreg.predict(X_test_scaled)

In [206]:
metrics.confusion_matrix(y_test,y_pred)

array([[31419,  3214],
       [   45,   140]], dtype=int64)

In [207]:

metrics.f1_score(y_test,y_pred)

0.07911839502684374

In [109]:
print(metrics.classification_report(y_test,y_pred))

             precision    recall  f1-score   support

        0.0       1.00      0.92      0.96     34633
        1.0       0.05      0.75      0.09       185

avg / total       0.99      0.92      0.95     34818



In [208]:
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format(logreg.score(X_test, y_test)))

Accuracy of logistic regression classifier on test set: 0.99


In [111]:

final.shape

(49739, 2)

In [112]:
y_pred.shape

(34818,)

In [113]:
logreg.fit(X, y)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [115]:
train_pred=logreg.predict(pre_train.drop(columns=["m13"],axis=0))

In [116]:
X.shape

(116058, 59)

In [117]:

test_pred=logreg.predict(pre_test.drop(columns=["m13"],axis=0))

In [118]:
metrics.f1_score(pre_train["m13"],train_pred)

0.918454565820538

In [136]:
metrics.f1_score(pre_train["m13"],train_pred)

0.09192093648052196

In [129]:

final["m13"]=test_pred

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [130]:
final.shape

(49739, 2)

In [131]:

final.head()

loan_id  m13
0  196706376986  0.0
1  786051527565  0.0
2  100072474882  1.0
3  328189712657  1.0
4  577598812667  1.0

In [132]:
final['m13'].value_counts()

0.0    45551
1.0     4188
Name: m13, dtype: int64

In [133]:
final.to_csv("C:\\Users\\266251\\Downloads\\Independent-Hack-AV-master\\Loansubmission.csv",index=False)

In [134]:
final.shape

(49739, 2)

In [142]:
sub=pd.read_csv("C:\\Users\\266251\\Independent-Hack-AV-master\\sample_submission.csv")

In [145]:
sub.head()

loan_id  m13
0  196706376986    0
1  786051527565    0
2  100072474882    1
3  328189712657    1
4  577598812667    1

In [144]:

sub["m13"]=test_pred.astype(int)

In [146]:
final.to_csv("C:\\Users\\266251\\Downloads\\Independent-Hack-AV-master\\sample_submission1.csv",index=False)

In [175]:
import statsmodels.api as sm

In [176]:
#Randomforest classifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=0)
rf.fit(X_train, y_train)
print("Accuracy on training set: {:.3f}".format(rf.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(rf.score(X_test, y_test)))

Accuracy on training set: 1.000
Accuracy on test set: 0.996


In [178]:
y_pred_train = rf.predict(X_train)

In [179]:
metrics.confusion_matrix(y_train,y_pred_train)

array([[80789,     0],
       [    0,   451]], dtype=int64)

In [185]:
metrics.f1_score(y_train,y_pred_train)

1.0

In [181]:
y_pred = rf.predict(X_test)

In [182]:
metrics.confusion_matrix(y_test,y_pred)

array([[34623,    10],
       [  126,    59]], dtype=int64)

In [183]:
metrics.f1_score(y_test,y_pred)

0.4645669291338583

In [186]:
rf.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [187]:
train_pred=rf.predict(pre_train.drop(columns=["m13"],axis=0))

In [188]:
test_pred=rf.predict(pre_test.drop(columns=["m13"],axis=0))

In [189]:
metrics.f1_score(pre_train["m13"],train_pred)

0.9992132179386309

In [191]:
sub=pd.read_csv("C:\\Users\\266251\\Independent-Hack-AV-master\\sample_submission.csv")

In [192]:
sub.head()

loan_id  m13
0  196706376986    0
1  786051527565    0
2  100072474882    0
3  328189712657    0
4  577598812667    0

In [193]:
sub["m13"]=test_pred.astype(int)

In [194]:
sub["m13"].value_counts()

0    49638
1      101
Name: m13, dtype: int64

In [195]:
final.to_csv("C:\\Users\\266251\\Downloads\\Independent-Hack-AV-master\\sample_submission2.csv",index=False)

In [210]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestClassifier(random_state = 42)
from pprint import pprint
# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

Parameters currently in use:

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 10,
 'n_jobs': 1,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}


In [211]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)

{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}


In [212]:

# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestClassifier()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X,y)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed: 29.5min
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed: 131.0min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed: 261.6min finished


RandomizedSearchCV(cv=3, error_score='raise',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          fit_params=None, iid=True, n_iter=100, n_jobs=-1,
          param_distributions={'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]},
          pre_dispatch='2*n_jobs', random_state=42, refit=True,
          return_train_score='warn', scoring=None, verbose=2)

In [213]:
rf_random.best_params_

{'n_estimators': 1000,
 'min_samples_split': 10,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 80,
 'bootstrap': False}

In [214]:
rf_random.best_score_

0.9960795464336797

In [217]:
rf_random.best_estimator_

RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=80, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [219]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy
base_model = RandomForestClassifier(n_estimators= 1000,min_samples_split= 10,min_samples_leaf= 1,max_features= 'sqrt',max_depth= 80,bootstrap= False)
base_model.fit(X,y)
base_accuracy = evaluate(base_model, pre_test.drop(columns=["m13"], test_labels)

best_random = rf_random.best_estimator_
random_accuracy = evaluate(best_random, test_features, test_labels)

print('Improvement of {:0.2f}%.'.format( 100 * (random_accuracy - base_accuracy) / base_accuracy))
#Improvement of 0.40%.

SyntaxError: invalid syntax (<ipython-input-219-6f2c9a6f3ea2>, line 15)

In [220]:
# Adaboost Classifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
#dtree = DecisionTreeClassifier(criterion='entropy',max_depth=2,random_state=42)

dtree = RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=80, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=False, random_state=42, verbose=0,
            warm_start=False)

adabst_fit = AdaBoostClassifier(base_estimator= dtree,
        n_estimators=600,random_state = 42)

In [222]:
dtree.fit(X_train, y_train)

RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=80, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [223]:
y_pred_train = dtree.predict(X_train)

In [224]:
metrics.confusion_matrix(y_train,y_pred_train)

array([[80786,     3],
       [  196,   255]], dtype=int64)

In [225]:
metrics.f1_score(y_train,y_pred_train)

0.7193229901269395

In [226]:
y_pred = dtree.predict(X_test)

In [227]:
metrics.confusion_matrix(y_test,y_pred)

array([[34624,     9],
       [  122,    63]], dtype=int64)

In [228]:
metrics.f1_score(y_test,y_pred)

0.490272373540856

In [230]:
dtree.fit(X, y)

RandomForestClassifier(bootstrap=False, class_weight=None, criterion='gini',
            max_depth=80, max_features='sqrt', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=10,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [231]:
train_pred=dtree.predict(pre_train.drop(columns=["m13"],axis=0))

In [232]:
test_pred=dtree.predict(pre_test.drop(columns=["m13"],axis=0))

In [233]:
sub=pd.read_csv("C:\\Users\\266251\\Independent-Hack-AV-master\\sample_submission.csv")

In [234]:
sub["m13"]=test_pred.astype(int)

In [235]:
sub["m13"].value_counts()

0    49634
1      105
Name: m13, dtype: int64

In [236]:
final.to_csv("C:\\Users\\266251\\Downloads\\Independent-Hack-AV-master\\sample_submissionADRF.csv",index=False)

In [196]:
# Function to calculate missing values by column# Funct 
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [197]:
# Missing values statistics
missing_values = missing_values_table(app_train)
missing_values.head(20)

Your selected dataframe has 30 columns.
There are 0 columns that have missing values.


Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

In [209]:
pre_train.head()

source_X  source_Y  source_Z  financial_institution_Anderson-Taylor  \
0         0         0         1                                      0   
1         0         1         0                                      0   
2         0         0         1                                      0   
3         1         0         0                                      0   
4         1         0         0                                      0   

   financial_institution_Browning-Hart  financial_institution_Chapman-Mcmahon  \
0                                    0                                      0   
1                                    0                                      0   
2                                    0                                      0   
3                                    0                                      0   
4                                    0                                      0   

   financial_institution_Cole, Brooks and Vincent  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   financial_institution_Edwards-Hoffman  \
0                                      0   
1                                      0   
2                                      0   
3                                      0   
4                                      0   

   financial_institution_Martinez, Duffy and Bird  \
0                                               0   
1                                               0   
2                                               0   
3                                               0   
4                                               0   

   financial_institution_Miller, Mcclure and Allen          ...            m9  \
0                                                0          ...             0   
1                                                0          ...             0   
2                                                0          ...             0   
3                                                0          ...             1   
4                                                0          ...             8   

   m10  m11  m12  m13  origination_date_quarter  origination_date_day  \
0    0    0    0  1.0                         1                     1   
1    0    1    0  1.0                         1                     1   
2    0    0    0  1.0                         1                     1   
3    1    1    1  1.0                         1                     1   
4    9   10   11  1.0                         1                     1   

   origination_date_Dayofweek  origination_date_is_weekend  \
0                           3                            0   
1                           6                            1   
2                           6                            1   
3                           2                            0   
4                           2                            0   

   origination_date_Year  
0                   2012  
1                   2012  
2                   2012  
3                   2012  
4                   2012  

[5 rows x 60 columns]

In [164]:
col=['source_X', 'source_Y', 'source_Z',
       'financial_institution_Thornton-Davis',
       'origination_date_Dayweek_Thursday',
       'origination_date_Dayweek_Wednesday', 'interest_rate',
       'unpaid_principal_bal','debt_to_income_ratio', 'm1',
       'm2', 'm5', 'm9', 'm11', 'm12',
       'origination_date_Dayofweek', 'origination_date_is_weekend']

In [165]:
logreg.fit(X_train[col], y_train)
logreg = LogisticRegression().fit(X_train[col], y_train)
print("Training set accuracy: {:.3f}".format(logreg.score(X_train[col], y_train)))
print("Test set accuracy: {:.3f}".format(logreg.score(X_test[col], y_test)))

Training set accuracy: 0.994
Test set accuracy: 0.995


In [166]:
y_pred_train = logreg.predict(X_train[col])

In [167]:

metrics.confusion_matrix(y_train,y_pred_train)

array([[80789,     0],
       [  451,     0]], dtype=int64)

In [168]:
metrics.recall_score(y_train,y_pred_train)

0.0

In [180]:
metrics.f1_score(y_test,y_pred)

0.08633093525179857